/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyHaulsRouteImport } from './routes/my-hauls'
import { Route as PostRouteImport } from './routes/post'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RetentionRouteImport } from './routes/retention'
import { Route as TakeRouteImport } from './routes/take'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WaiverRouteImport } from './routes/waiver'
import { Route as JobIdRouteImport } from './routes/job.$id'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHaulsRoute = MyHaulsRouteImport.update({
  id: '/my-hauls',
  path: '/my-hauls',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RetentionRoute = RetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeRoute = TakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiverRoute = WaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const JobIdRoute = JobIdRouteImport.update({
  id: '/job/$id',
  path: '/job/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-hauls': typeof MyHaulsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/retention': typeof RetentionRoute
  '/take': typeof TakeRoute
  '/verify': typeof VerifyRoute
  '/waiver': typeof WaiverRoute
  '/job/$id': typeof JobIdRoute
  '/track/$token': typeof TrackTokenRoute
  '/u/$id': typeof UIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-hauls': typeof MyHaulsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/retention': typeof RetentionRoute
  '/take': typeof TakeRoute
  '/verify': typeof VerifyRoute
  '/waiver': typeof WaiverRoute
  '/job/$id': typeof JobIdRoute
  '/track/$token': typeof TrackTokenRoute
  '/u/$id': typeof UIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-hauls': typeof MyHaulsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/retention': typeof RetentionRoute
  '/take': typeof TakeRoute
  '/verify': typeof VerifyRoute
  '/waiver': typeof WaiverRoute
  '/job/$id': typeof JobIdRoute
  '/track/$token': typeof TrackTokenRoute
  '/u/$id': typeof UIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/inbox'
    | '/login'
    | '/my-hauls'
    | '/post'
    | '/profile'
    | '/retention'
    | '/take'
    | '/verify'
    | '/waiver'
    | '/job/$id'
    | '/track/$token'
    | '/u/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/inbox'
    | '/login'
    | '/my-hauls'
    | '/post'
    | '/profile'
    | '/retention'
    | '/take'
    | '/verify'
    | '/waiver'
    | '/job/$id'
    | '/track/$token'
    | '/u/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/inbox'
    | '/login'
    | '/my-hauls'
    | '/post'
    | '/profile'
    | '/retention'
    | '/take'
    | '/verify'
    | '/waiver'
    | '/job/$id'
    | '/track/$token'
    | '/u/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MyHaulsRoute: typeof MyHaulsRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  RetentionRoute: typeof RetentionRoute
  TakeRoute: typeof TakeRoute
  VerifyRoute: typeof VerifyRoute
  WaiverRoute: typeof WaiverRoute
  JobIdRoute: typeof JobIdRoute
  TrackTokenRoute: typeof TrackTokenRoute
  UIdRoute: typeof UIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hauls': {
      id: '/my-hauls'
      path: '/my-hauls'
      fullPath: '/my-hauls'
      preLoaderRoute: typeof MyHaulsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retention': {
      id: '/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof RetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/take': {
      id: '/take'
      path: '/take'
      fullPath: '/take'
      preLoaderRoute: typeof TakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$id': {
      id: '/job/$id'
      path: '/job/$id'
      fullPath: '/job/$id'
      preLoaderRoute: typeof JobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MyHaulsRoute: MyHaulsRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  RetentionRoute: RetentionRoute,
  TakeRoute: TakeRoute,
  VerifyRoute: VerifyRoute,
  WaiverRoute: WaiverRoute,
  JobIdRoute: JobIdRoute,
  TrackTokenRoute: TrackTokenRoute,
  UIdRoute: UIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
